---

num_rounds: 2
num_clients: 100
batch_size: 16
test_batch_size: 128
val_ratio: 0.1

dataset: "mnist"
clients_per_round_fit: 10
clients_per_round_val: 25
num_classes: 10
proximal_mu: 1
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
