---

num_clients: 20
num_rounds: 10
client_resources:
  num_cpus: 2
  num_gpus: 0.2

config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1

dataset:
  name: "alkzar90/NIH-Chest-X-ray-dataset"
  partitioner:
    name: "DirichletPartitioner"
    alpha: 1.0