---

seed: 42
num_clients: 50
fraction_train_clients: 0.1
num_rounds: 100
client_resources:
  num_cpus: 24
  num_gpus: 0.125  # Fraction of clients per gpu

config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
  local_batch_size: 32

dataset:
  name: "albertvillanova/medmnist-v2"  # dataset name on Hugging Face [ "BahaaEldin0/NIH-Chest-Xray-14", BahaaEldin0/NIH-Chest-Xray-14-with-Augmentation, "hf-vision/chest-xray-pneumonia", "marmal88/skin_cancer", SilpaCS/Augmented_alzheimer]
  subset: "bloodmnist"
  data_dir: "./data"
  seed: 123
  partitioner:
    name: "IiD"  # Type of data partition ["PathologicalPartitioner", "DirichletPartitioner", "Iid"]
    alpha: 0.1  # heterogeneity degree *DirichletPartitioner
    num_classes_per_partition: 2  # number of classes per partition *PathologicalPartitioner

model:
  num_classes: 9

dp:
  delta: 0.1
  epsilon: 0.1
  sensitivity: 0.1
  clipping_norm: 0.1

plot:
  smoothing_window: 1