---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

defaults:
  - _self_
  - strategy: fednova
  - optimizer: hybrid

var_local_epochs: False
datapath: fednova/data/
checkpoint_path: fednova/checkpoints/
num_clients: 8
num_epochs: 2
num_rounds: 10
batch_size: 16
NIID: True
alpha: 0.1
var_min_epochs: 2
var_max_epochs: 5
lr_scheduling: True
seed: 1
mode: train

local_dp:
  clipping_norm: 0.1
  sensitivity: 0.1
  epsilon: 0.1
  delta: 0.3

model:
  _target_: fednova.models.VGG

client_resources:
  num_cpus: 8
  num_gpus: 1

hydra:
  sweep:
    dir: multirun
    subdir: ${hydra.job.override_dirname}/${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
          - num_rounds
        kv_sep: _
        item_sep: _
