---
seed: 42
num_clients: 20
num_rounds: 10
client_resources:
  num_cpus: 2
  num_gpus: 0.2  # Fraction of clients per gpu

strategy:
  proximal_mu: 1

config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1
  client_batch: 32

dataset:
  name: "albertvillanova/medmnist-v2"  # dataset name on Hugging Face [ "BahaaEldin0/NIH-Chest-Xray-14", BahaaEldin0/NIH-Chest-Xray-14-with-Augmentation, "hf-vision/chest-xray-pneumonia", "marmal88/skin_cancer", SilpaCS/Augmented_alzheimer]
  subset: "PathMNIST"  # dataset name on Hugging Face [ "BahaaEldin0/NIH-Chest-Xray-14", "hf-vision/chest-xray-pneumonia"]
  data_dir: "./data"
  partitioner:
    name: "DirichletPartitioner"  # Type of data partition ["PathologicalPartitioner", "DirichletPartitioner", "Iid"]
    alpha: 1.0  # heterogeneity degree *DirichletPartitioner
    num_classes_per_partition: 2  # number of classes per partition *PathologicalPartitioner

model:
  num_classes: 9